[common]
hotkey4Show="#^+s"
skipRecord ="" 
; | 分割要过滤的字符，哪些按键要忽略记录
skipCtrlKey = 1
; 是否忽略单独的控制键，不记录
onlyRecordKey = 0
; 只记录按键，不显示
ctrlState  = 1
 ; 是否显示 控制键状态，如果出现则显示
serverPort  = 9999
 ; 后端服务端口号
[dialog]
guiWidth  =  240
color = 000000
 ; 宽度
