export default {
  'zh-CN': {
    title: '按键显示工具后台',
    lang: 'zh-CN',
    theme1:'深色',
    theme2:'浅色',
    menu:{
      home:'主页',
      setting:'设置',
      setting1:'个人喜好',
      setting2:'按键界面',
      setting3:'统计配置',
      setting4:'按键清单',
      setting5:'参数变化',
      stat: '数据',
      stat1: '今日数据',
      stat2: '历史分析',
      stat3: '数据趋势',
      stat4: '数据处理',
    },
	keyIntro:`按键说明:!表示Alt , #表示windows, +表示shift, ^ 表示Ctrl, < 表示左，>表示右，可自由组合。 
              比如 ^#F5 表示按下ctrl+win+F5键,<^<+D表示按下左侧的Ctrl+左侧Shift+字母键D`,
	intro1:'通用设置',
	intro2:'要忽略记录的按键',
	intro3:'是否忽略单独按下的控制键',
	intro4:'控制键主要为 Ctrl,Alt,Shift,Win',
	intro5:'是否显示和记录鼠标事件',
	intro6:'是否记录鼠标移动距离',
	intro7:'是否显示键盘和鼠标按键 **',
	intro8:'是否记录按键,关闭时将不启动后台服务',
	intro9:'是否显示控制键状态 **',
	intro10:'控制键主要为 Ctrl,Alt,Shift,Win等，按下则显示',
	intro11:'后端服务端口号',
	intro12:'按键显示仅针对活跃窗口',
	intro13:'使用正则匹配窗口进程名',
	intro14:'按键临时显示开关快捷键',
	intro15:'修改后重启程序生效。',
	intro16:'手工输入按键',
	intro17:'按键实时显示界面',
	intro18:'宽度',
	intro19:'高度',
	intro20:'为0表示自适应',
	intro21:'背景色和整体透明度',
	intro22:'鼠标穿透',
	intro23:'可以点击到提示框下方的窗体',
	intro24:'字体',
	intro25:'选择系统的字体',
	intro26:'字体大小',
	intro27:'字体类型',
	intro28:'字体颜色',
	intro29:'显示多少毫秒消失',
	intro30:'窗体间隔毫秒',
	intro31:'按键弹框位置',
	intro32:'提示框出现的屏幕位置',
	intro33:'左上',
	intro34:'右上',
	intro35:'左下',
	intro36:'右下',
	intro37:'窗口移动方向',
	intro38:'横向或垂直移动',
	intro39:'位置X调整',
	intro40:'横向位置调整，负数表示往左，正数表示往右',
	intro41:'位置Y调整',
	intro42:'纵向位置调整，负数表示往上，正数表示往下',
	intro43:'是否进行DPI缩放',
	intro44:'第几个屏幕',
	intro45:'屏幕信息为',
	intro46:'提示窗口间的间隔(px)',
	intro47:'是否有边框',
	intro48:'按键分隔符,用于按键间的显示分割',
	intro49:'推荐用空格',
	intro50:'长按显示,主要用于控制键,如Ctrl、Alt、LWin、Shift、RWin、CapsLock等',
	intro51:'显示控制键X位置',
	intro52:'显示控制键Y位置',
	intro53:'控制键字体大小',
	intro54:'控制键清单,如Ctrl,Alt,LWin,Shift,RWin,CapsLock,NumLock,ScrollLock等',
	intro55:'哪些按键不会显示，但会记录',
	intro56:'数据统计界面的相关参数设置',
	intro57:'第一个屏幕大小(英寸)',
	intro58:'用于计算光标在屏幕的移动距离',
	intro59:'鼠标DPI',
	intro60:'用于计算实际鼠标移动距离',
	intro61:'按键名',
	intro62:'显示的按键符号',
	intro63:'不显示不记录',
	intro64:'不显示但记录',
	intro65:'只显示不记录',
	intro66:'既显示也记录',
	intro67:'普通',
	intro68:'粗体',
	intro69:'斜体',
	intro70:'删除线',
	intro71:'下划线',
	intro72:'未获取屏幕信息,请重启客户端',
	intro73:'数据载入中',
	intro74:'成功载入数据',
	intro75:'数据保存中',
	intro76:'成功保存数据',
	intro77:'',
	intro78:'修改前',
	intro79:'修改后',
	intro80:'展开',
	intro81:'还原数据',
	intro82:'保存数据',
	intro83:'存在差异，保存后客户端可能自动重启以应用新参数',
	intro84:'没有改变',
	intro85:'数据读取失败!',
	intro86:'键盘显示',
	intro87:'按键次数清单',
	intro88:'键名',
	intro89:'按键说明',
	intro90:'统计数据',
	intro91:'当前',
	intro92:'每次客户端重启会产生一个新的时间，当天时间段，从 ',
	intro93:'到 ',
	intro94:'鼠标移动距离(像素)',
	intro95:'鼠标屏幕移动距离(米)',
	intro96:'鼠标物理距离(米)',
	intro97:'鼠标移动信息',
	intro98:'距离说明',
	intro99:'数据统计键盘',
	intro100:`键盘由数组构成，数组中每个元素为4位数组，第一位表示X坐标，第二位是Y坐标，
	第三位是显示在键盘上的符号(可能通过按键清单转义)，第四位是对应的真实按键信息，支持多个按键用空格分割，不写则以第三位为准 \n\n 支持下拉框中直接输入后回车创建新键盘`,
	intro101:'键盘定义不是规范的格式',
	intro102:'每行键盘定义必须是数组，且长度为2-4位:',
	intro103:'每行键盘开头2个必须是坐标数字:',
	intro104:'应用',
	intro105:'保存新建',
	intro106:'删除',
	intro107:'成功应用新键盘，你可以在数据模块查看',
	intro108:'保存更新',
	intro109:'确定',
	intro110:'取消',
	intro111:'成功',
	intro112:'请选择日期',
	intro113:'查询',
	intro114:'鼠标移动距离统计',
	intro115:'鼠标/键盘按键合计',
	intro116:`Top N 按键统计`,
	intro117:'日期格式不合规',
	intro118:'在数据趋势中按键统计前N个',
	intro119:`
	声明 : 本工具不联网，只保存统计信息，不记录具体内容，不会收集任何数据到服务器上

	功能 : 实时显示按键情况，统计历史按键
	数据 : 统计数据只保存在本地的 httpdist\\dist\\records.db 文件中，此文件为sqlite3格式
	代码 : 全部开源 https://github.com/pattazl/showKeyBoard 
	架构 : 按键监控采用autohotkey + windows API, 设置和统计界面显示用html , node做websocket/http 服务通讯
	`,
	intro120:'选择要删除的当天时间',
	intro121:'选择要删除的历史日期',
	intro122:'确定删除:',
	intro123:'导出配置和记录',
	intro124:'导入配置和记录,将导致重启客户端',
	intro125:'上传时间',
	intro126:'上传文件名',
	intro127:'上传过程信息',
	intro128:'导入设置成功',
	intro129:'导入设置失败',
	intro130: '保存失败',
	intro131: '普通按键按住不放,重复次数上限(次)',
	intro132: '控制键按键不放,重复次数上限(次)',
	intro133: '每多少秒自动将按键信息保存到数据库中',
	intro134: '远程控制模式',
	intro135: '禁止远程',
	intro136: '可远程查看',
	intro137: '可远程查看和设置',
	intro138: '是否显示http调试框',
	intro139: '如果允许，则可通过如下地址来远程访问或控制',
	intro140: '在密码输入框中使用掩码*，不显示密码',
	intro141: '仅支持windows客户端的原生密码输入框，不支持浏览器或定制密码输入框',
	intro142: ',更新时间: ',
	intro143: '合并左右控制键',
	intro144: '左右控制键分别显示',
	intro145: '应用显示前N个',
	intro146: '应用执行程序全路径',
	intro147: '应用程序显示名',
	intro148: '应用程序名转换清单，默认取执行程序文件名,支持正则表达式用Reg:开头配置',
	intro149: '应用按键统计',
	intro150: '跳过没有数据的日期',
	intro151: '用空数据填充日期',
	intro152: '应用操作合计TOP N',
	intro153: '应用鼠标显示TOP N',
	intro154: '应用键盘显示TOP N',
	intro155: '是否发送应用信息，以用于统计不同应用的使用情况',
	intro156: '应用程序路径',
	intro157: '数据类型',
	intro158: '相同名称的应用是否进行合并统计(展示)',
	intro159: '单日期查询',
	intro160: '时间段到',
	intro161: '今日数据中，数据过N毫秒后才会显示到界面上，避免频繁刷新',
	intro162: '默认语言',
	intro163: '自动备份数据保留天数',
	intro164: '如果为0则不进行自动备份,备份在安装目录下的backup目录，每次客户端启动均备份一次',
	intro165: '每分钟操作数',
	intro166: '每小时操作数',
	intro167: '应用时长(分钟)',
	intro168: ' , 请点击应用时长中的应用显示详细',
	intro169: '分钟数据保留天数',
	intro170: '每分钟应用操作统计',
	intro171: '每小时应用操作统计',
	intro172: '今日数据中，界面操作时N毫秒内界面不刷新，避免影响操作',
	intro173: '操作中，?秒后刷新',
	intro174: '是否显示当前激活的应用全路径 **',
	intro175: '应用全路径显示的X位置 **',
	intro176: '应用全路径显示的Y位置 **',
	intro177: '客户端通讯异常，请重启客户端或重启系统',
	intro178: '后台通讯中...',
	intro179: '仅针对指定进程记录按键,注:显示是基于按键的',
	intro180: '显示全部按键',
	intro181: '显示剩余按键',
	intro182: '应用按键明细',
	intro183: '跟随激活窗口',
	intro184: '是否上传时根据规则转换应用名称',
	intro185: '程序转换后名称，留空表示忽略此程序',
	intro186: '预览显示按键位置, 受本模块绝大部分参数及标记为**的参数影响',
	intro187: '点击暂停/启动背景切换',
	intro188: '背景完全透明(影响按键和长按显示)',
	intro189: '圆角矩形半径',
	intro190: '0表示无圆角，可能会影响边框显示',
	intro191: '多少毫秒后渐变消失，0表示无渐变直接消失',
	intro192: '显示多少条的历史按键记录',
	intro193: '最近历史按键记录',
	intro194: '是否启动时候托盘提示',
	intro195: '游戏手柄支持',
	intro196: '不启用',
	intro197: '方案1，支持旧游戏手柄，手柄数量变化会重启客户端',
	intro198: '方案2，支持新手柄协议 win10以上，推荐',
	intro199: '每日鼠标键盘按键总和',
	intro200: '移动距离(像素)',
	intro201: '屏幕移动距离(米)',
	intro202: '物理移动距离(米)',
	intro203: '鼠标按键总和',
	intro204: '键盘按键总和',
	intro205: '共享文件所在路径',
	intro205_1: '可将其他设备的记录同步到此目录，支持相对/绝对目录',
	intro206: '共享文件名',
	intro206_1: '留空，默认使用计算名',
	intro207: '生成共享文件间隔小时数',
	intro207_1: '0=不生成，>0 每次启动后均会自动检查，覆盖方式生成新文件，生成的文件可共享给其他设备，从而实现同时查看多个设备',
	intro208: '共享文件生成后将自动执行的命令',
	intro208_1: '可用于备份完成后执行相关命令，将自动处理其他设备的新文件',

  },
  'en-US': {
    title: 'Show Keyboard Management',
    lang: 'en-US',
    theme1:'Dark',
    theme2:'Light',
    menu:{
      home:'Home',
      setting:'Setting',
      setting1:'Preference',
      setting2:'Popup UI',
      setting3:'Stat Para',
      setting4:'KeyMap',
      setting5:'Changed',
      stat: 'Data',
      stat1: 'Today',
      stat2: 'History',
      stat3: 'Statistics',
      stat4: 'Manage',
    },
	keyIntro: `Key Instructions: ! = Alt, # = Windows, + = Shift, ^ = Ctrl, < = Left, > = Right. They can be combined freely. For example, ^#F5 represents pressing Ctrl+Win+F5, <^<+D represents pressing Left Ctrl+Left Shift+the letter key D.`,

	intro1: 'General Settings',
	intro2: 'Ignore recorded keystrokes',
	intro3: 'Ignore individual press control keys',
	intro4: 'Control keys mainly include Ctrl, Alt, Shift, Win',
	intro5: 'Show and record mouse events',
	intro6: 'Record mouse movement distance',
	intro7: 'Display mouse and keyboard press **',
	intro8: 'Record keyboard press,the backend service will not be launched when closed',
	intro9: 'Display control key status **',
	intro10: 'Control keys mainly include Ctrl, Alt, Shift, Win (display if pressed)',
	intro11: 'Backend service port number',
	intro12: 'Keystroke display only for active window',
	intro13: 'Use regular expression to match window process names',
	intro14: 'Shortcut key for toggling keystroke temporary display',
	intro15: 'Changes take effect after program restarts.',
	intro16: 'Manually enter keystrokes',
	intro17: 'Real-time display interface for keystrokes',
	intro18: 'Width',
	intro19: 'Height',
	intro20: '0 means auto-adaptation',
	intro21: 'Background color and whole transparency',
	intro22: 'Mouse Penetration',
	intro23: 'Can click the app under the Popup',
	intro24: 'Font',
	intro25: 'Choose system fonts',
	intro26: 'Font size',
	intro27: 'Font type',
	intro28: 'Font color',
	intro29: 'Popup Fade delay(ms)',
	intro30: 'Interval of new Popup(ms)',
	intro31: 'Up, down, left, right position',
	intro32: 'Screen position of Popup appearance',
	intro33: 'Top-left',
	intro34: 'Top-right',
	intro35: 'Bottom-left',
	intro36: 'Bottom-right',
	intro37: 'Popup movement direction',
	intro38: 'Horizontal or vertical movement',
	intro39: 'Adjust position X',
	intro40: 'Horizontal position adjustment. Negative numbers indicate leftward movement and positive numbers indicate rightward movement.',
	intro41: 'Adjust Position Y',
	intro42: 'Vertical position adjustment. Negative numbers indicate upward movement and positive numbers indicate downward movement.',
	intro43: 'Enable DPI scale',
	intro44: 'Screen number',
	intro45: 'Screen Info is',
	intro46: 'Margin of Popup(px)',
	intro47: 'Have border',
	intro48: 'Key separator, used for displaying separation between keys',
	intro49: 'Recommended to use a space',
	intro50: 'Long press display, mainly used for control keys such as Ctrl, Alt, LWin, Shift, RWin, CapsLock etc.',
	intro51: 'Control key Panel X position',
	intro52: 'Control key Panel Y position',
	intro53: 'Control key font size',
	intro54: 'Control key list, such as Ctrl,Alt,LWin,Shift,RWin,CapsLock,NumLock,ScrollLock etc.',
	intro55: 'Which keys will not be displayed, but will be recorded',
	intro56: 'Parameters setting for the data statistics interface',
	intro57: 'First Screen size (in inches)',
	intro58: 'Used to calculate the cursor movement distance on the screen',
	intro59: 'Mouse DPI',
	intro60: 'Used to calculate the actual mouse movement distance',
	intro61: 'Key name',
	intro62: 'Symbol displayed for the key',
	intro63: 'Do not display or record',
	intro64: 'Do not display but record',
	intro65: 'Only display, do not record',
	intro66: 'Display and record',
	intro67: 'Normal',
	intro68: 'Bold',
	intro69: 'Italic',
	intro70: 'Strikethrough',
	intro71: 'Underline',
	intro72: 'Can not get Screen Info,please restart!',
	intro73: 'Data loading...',
	intro74: 'Loaded sucess!',
	intro75: 'Data saving...',
	intro76: 'Saved sucess!',
	intro77: '',
	intro78: 'Before',
	intro79: 'After',
	intro80: 'Expand',
	intro81: 'Reset',
	intro82: 'Save',
	intro83: 'Have changed, the client maybe restart for appling new parameter after saved',
	intro84: 'No changed',
	intro85:'Read data fail!',
	intro86:'Show in keyboard',
	intro87:'List of Keypress',
	intro88:'KeyName',
	intro89:'Key Description',
	intro90:'Key Count',
	intro91:'Now',
	intro92:'Will create a new time when client restart, today Time Range, from ',
	intro93:'to ',
	intro94:'Mouse movement distance (pixels)',
	intro95:'Mouse screen movement distance (meters)',
	intro96:'Mouse physical distance (meters)',
	intro97:'Mouse movement info',
	intro98:'Desc of distance',
	intro99:'Keyboard for data statistics',
	intro100:`The keyboard's define is composed of an array, each element is a 4-digit array. The first digit = X coordinate and the second digit = Y coordinate,
	The third digit is the symbol displayed on the keyboard (can be replaced by the key list), 
	and the fourth digit is the corresponding key(support multi,split by space), if empty, the third digit is default \n\n You can type and enter the new keyboard name in DropDownList`,
	intro101:"The keyboard's define is not valid format!",
	intro102:'Every keyboard define must be array, and lenth is 2-4 digits:',
	intro103:'1,2 digit of every keyboard define must be number:',
	intro104:'Apply',
	intro105:'Save New',
	intro106:'Delete',
	intro107:'Apply keyboard successful, you can check in data menu',
	intro108:'Save Update',
	intro109:'Confirm',
	intro110:'Cancel',
	intro111:'Successful',
	intro112:'Select Date',
	intro113:'Query',
	intro114:'Mouse Distance',
	intro115:'The sum of Mouse/keyboard Keypress ',
	intro116: `Top N of keyboard keypress`,
	intro117:'The format of date is invalid',
	intro118:'Top N in keyboard statistic',
	intro119:`
	Declaration: This tool is offline, save statistical information only, and will not collect any data on the server

	Functionality: Real-time display of key press information and tracking of historical key presses.
	Data: The statistic data is saved in a local file named "records.db" located in the "httpdist\\dist" directory. This file is in SQLite3 format.
	Code: The entire codebase is open source and available at https://github.com/pattazl/showKeyBoard.
	Architecture: Key monitoring is done using autohotkey + Windows API. The settings and statistics interface is displayed using HTML, and communication between the interface and server is WebSocket and HTTP services by Node.js.
	`,
	intro120:"Please select start time of today",
	intro121:'Please select the day of history',
	intro122:'Are you sure delete:',
	intro123:'Export Setting and Records',
	intro124:'Import Setting and Records, will restart client',
	intro125:'Upload Time',
	intro126:'Upload filename',
	intro127:'Upload info in server',
	intro128:'Import Setting Successful',
	intro129:'Import Setting Fail!',
	intro130: 'Saved Fail!',
	intro131: 'Max times for repeat normal keys when keep press',
	intro132: 'Max times for repeat control keys when keep press',
	intro133: 'Interval seconds automatically saved to the database',
	intro134: 'Remote control mode',
	intro135: 'Prevent remote',
	intro136: 'Only remote read  ',
	intro137: 'Remote read and set',
	intro138: 'Show debug http window',
	intro139: 'You can visit manangement page by follow address when permit',
	intro140: 'Display mask * when in password input,not display the password',
	intro141: 'Only support native password input, not support browsers or custom password input',
	intro142: ',Update Time:',
	intro143: 'Merge left and right control keys',
	intro144: 'Displayed left and right control keys ',
	intro145: 'App display Top N',
	intro146: 'App full path',
	intro147: 'App display Name',
	intro148: 'App name mapping list, basename is default, start with Reg: for regular expression support',
	intro149: 'App keypress statistic',
	intro150: 'Ignore date that no data',
	intro151: 'Fill date that no data',
	intro152: 'App operate accumulate TOP N',
	intro153: 'App mouse operate TOP N',
	intro154: 'App keystroke operate TOP N',
	intro155: 'Whether send App Info for App statistic',
	intro156: 'App path',
	intro157: 'Data Type',
	intro158: 'Whether the same app name will be merged in statistic(Display)',
	intro159: 'Single date query',
	intro160: 'Query date until',
	intro161: 'Will fresh the data after N ms on Today panel, avoid refreshing too frequently',
	intro162: 'Default language',
	intro163: 'Keep days when auto backup data',
	intro164: 'If zero will not backup data, backup fold is install dir/backup, will backup once when client launch',
	intro165: 'Operate by minutes',
	intro166: 'Operate by hours',
	intro167: 'App usage duration(minutes)',
	intro168: ' , Please click the usage duration for App detail',
	intro169: 'Keep days for Minute data',
	intro170: 'Apps Operate by minutes',
	intro171: 'Apps Operate by hours',
	intro172: 'Stop refresh in N ms when click on Today panel, Avoid affecting operations',
	intro173: 'In operating, refresh in ? seconds',
	intro174: 'Whether show activated App path **',
	intro175: 'Tooltip of App path X position **',
	intro176: 'Tooltip of App path Y position **',
	intro177: 'Communication of Client error, please restart the client or system',
	intro178: 'Communicate with backend...',
	intro179: 'Record for defined active process , note: display is based on record',
	intro180: 'Show All keys',
	intro181: 'Show Left keys',
	intro182: 'App keypress detail',
	intro183: 'Follow Active App',
	intro184: 'Whether convert the application name by rules when uploading',
	intro185: 'The name of the app after conversion. Blank means ignoring this app.',
	intro186: 'Preview UI positions. It is affected by most of the parameters in this module and the parameters marked with **.',
	intro187: 'Click to pause/start the background switching',
	intro188: 'Background color is transparent(for keypress and long press display)',
	intro189: 'Radius of the rounded rectangle',
	intro190: '0 indicates no rounded corners, may affect the display of the border',
	intro191: 'Milliseconds later will fade out? 0 means disappear directly without fading',
	intro192: 'Max Number of historical keystrokes to display',
	intro193: 'The historical keystrokes',
	intro194: 'Whether traytip when starting',
	intro195: 'Joystick support',
	intro196: 'Disabled',
	intro197: 'Solution 1, support old xbox360 protocol, and the client will be restarted if the number of handles changes',
	intro198: 'Solution 2, support new xbox360 protocol(2013 and later) , win10 or above, recommended',
	intro199: 'Sum of daily mouse and keyboard',
	intro200: 'Pix Distance',
	intro201: 'Screen Distance(Meter)',
	intro202: 'Physical Distance(Meter)',
	intro203: 'Sum of mouse',
	intro204: 'Sum of keyboard',
	intro205: 'Path of the shared file',
	intro205_1: 'Records from other devices can be synchronized to this directory, supporting relative/absolute paths',
	intro206: 'Shared file name',
	intro206_1: 'Leave blank to use the computer name by default',
	intro207: 'Interval hours for generating shared files',
	intro207_1: '0 = not generate, >0 will automatically check after each startup, generate new files in an overwriting manner, and the generated files can be shared with other devices to realize simultaneous viewing of multiple devices',
	intro208: 'Commands to be automatically executed after the shared file is generated',
	intro208_1: 'Can be used to execute relevant commands after backup completion, and will automatically process new files from other devices'
  }
};
