import { h } from 'vue';
import { NP, NText, NUl, NA, NPopover, NDivider, NOl } from 'naive-ui';

export default {
  'zh-CN': {
    title: '按键显示工具后台',
    lang: 'zh-CN',
    theme1:'深色',
    theme2:'浅色',
    menu:{
      home:'主页',
      setting:'设置',
      setting1:'个人喜好',
      setting2:'按键界面',
      setting3:'统计参数',
      setting4:'按键清单',
      setting5:'保存参数',
      stat: '数据',
      stat1: '今日数据',
      stat2: '历史分析',
      stat3: '数据趋势',
      stat4: '数据导出',
    },
	keyIntro:`按键说明:!表示Alt , #表示windows, +表示shift, ^ 表示Ctrl, < 表示左，>表示右，可自由组合。 
              比如 ^#F5 表示按下ctrl+win+F5键,<^<+D表示按下左侧的Ctrl+左侧Shift+字母键D`,
	intro1:'通用设置',
	intro2:'要忽略记录的按键',
	intro3:'是否忽略单独的控制键',
	intro4:'控制键主要为 Ctrl,Alt,Shift,Win',
	intro5:'是否显示和记录鼠标事件',
	intro6:'是否记录鼠标移动距离',
	intro7:'是否显示按键',
	intro8:'是否记录按键',
	intro9:'是否显示控制键状态',
	intro10:'控制键主要为 Ctrl,Alt,Shift,Win  出现则显示',
	intro11:'后端服务端口号',
	intro12:'按键显示仅针对活跃窗口',
	intro13:'使用正则匹配窗口进程名',
	intro14:'按键临时显示开关快捷键',
	intro15:'定义快捷键, 修改后重启程序生效。',
	intro16:'手工输入按键',
	intro17:'按键实时显示界面',
	intro18:'宽度',
	intro19:'高度',
	intro20:'为0表示自适应',
	intro21:'背景色和透明度',
	intro22:'鼠标穿透',
	intro23:'可以点击到提示框下方的窗体',
	intro24:'字体',
	intro25:'选择系统的字体',
	intro26:'字体大小',
	intro27:'字体类型',
	intro28:'字体颜色',
	intro29:'显示多少毫秒消失',
	intro30:'窗体间隔毫秒',
	intro31:'按键弹框位置',
	intro32:'提示框出现的屏幕位置',
	intro33:'左上',
	intro34:'右上',
	intro35:'左下',
	intro36:'右下',
	intro37:'窗口移动方向',
	intro38:'横向或垂直移动',
	intro39:'位置X调整',
	intro40:'横向位置调整，负数表示往左，正数表示往右',
	intro41:'位置Y调整',
	intro42:'纵向位置调整，负数表示往上，正数表示往下',
	intro43:'是否进行DPI',
	intro44:'第几个屏幕',
	intro45:'屏幕信息为',
	intro46:'提示窗口间的间隔(px)',
	intro47:'是否有细边框',
	intro48:'按键分隔符,用于按键间的显示分割',
	intro49:'推荐用空格',
	intro50:'长按显示,主要用于控制键,如Ctrl、Alt、LWin、Shift、RWin、CapsLock等',
	intro51:'控制键X位置',
	intro52:'控制键Y位置',
	intro53:'控制键字体大小',
	intro54:'控制键清单',
	intro55:'哪些按键不会显示，但会记录',
	intro56:'数据统计界面的相关参数设置',
	intro57:'第一个屏幕大小(英寸)',
	intro58:'用于计算光标在屏幕的移动距离',
	intro59:'鼠标DPI',
	intro60:'用于计算实际鼠标移动距离',
	intro61:'按键名',
	intro62:'显示的按键符号',
	intro63:'不显示不记录',
	intro64:'不显示但记录',
	intro65:'只显示不记录',
	intro66:'既显示也记录',
	intro67:'普通',
	intro68:'粗体',
	intro69:'斜体',
	intro70:'删除线',
	intro71:'下划线',
	intro72:'未获取屏幕信息,请重启客户端',
	intro73:'数据载入中',
	intro74:'成功载入数据',
	intro75:'数据保存中',
	intro76:'成功保存数据',
	intro77:'',
	intro78:'修改前',
	intro79:'修改后',
	intro80:'展开',
	intro81:'还原数据',
	intro82:'保存数据',
	intro83:'存在差异，保存后客户端可能自动重启以应用新参数',
	intro84:'没有改变',
	intro85:'数据读取失败!',
	intro86:'键盘显示',
	intro87:'其他按键统计',
	intro88:'键名',
	intro89:'按键说明',
	intro90:'统计数据',
	intro91:'当前',
	intro92:'每次客户端重启会产生一个新的时间，当天时间段，从 ',
	intro93:'到 ',
	intro94:'鼠标移动距离(像素)',
	intro95:'鼠标屏幕移动距离(米)',
	intro96:'鼠标物理距离(米)',
	intro97:'鼠标移动信息',
	intro98:'距离说明',
	intro99:'数据统计键盘',
	intro100:`键盘由数组构成，数组中每个元素为4位数组，第一位表示X坐标，第二位是Y坐标，
	第三位是显示在键盘上的符号(可能通过按键清单转义)，第四位是对应的真实按键信息，不写则以第三位为准 \n\n 支持下拉框中直接输入后回车创建新键盘`,
	intro101:'键盘定义不是规范的格式',
	intro102:'每行键盘定义必须是数组，且长度为2-4位:',
	intro103:'每行键盘开头2个必须是坐标数字:',
	intro104:'应用',
	intro105:'保存新建',
	intro106:'删除',
	intro107:'成功应用新键盘，你可以在数据模块查看',
	intro108:'保存更新',
	intro109:'确定',
	intro110:'取消',
	intro111:'成功',
	intro112:'请选择日期',
	intro113:'查询',
	intro114:'鼠标移动距离统计',
	intro115:'鼠标/键盘按键合计',
	intro116:'Top10按键统计',
	intro117:'日期格式不合规',

  },
  'en-US': {
    title: 'Show Keyboard Server',
    lang: 'en-US',
    theme1:'Dark',
    theme2:'Light',
    menu:{
      home:'Home',
      setting:'Setting',
      setting1:'Preference',
      setting2:'Popup UI',
      setting3:'Stat Para',
      setting4:'KeyMap',
      setting5:'Save',
      stat: 'Data',
      stat1: 'Today',
      stat2: 'History',
      stat3: 'Statistics',
      stat4: 'Export',
    },
	keyIntro: `Key Instructions: ! = Alt, # = Windows, + = Shift, ^ = Ctrl, < = Left, > = Right. They can be combined freely. For example, ^#F5 represents pressing Ctrl+Win+F5, <^<+D represents pressing Left Ctrl+Left Shift+the letter key D.`,

	intro1: 'General Settings',
	intro2: 'Ignore recorded keystrokes',
	intro3: 'Ignore individual control keys',
	intro4: 'Control keys mainly include Ctrl, Alt, Shift, Win',
	intro5: 'Show and record mouse events',
	intro6: 'Record mouse movement distance',
	intro7: 'Display keystrokes',
	intro8: 'Record keystrokes',
	intro9: 'Display control key status',
	intro10: 'Control keys mainly include Ctrl, Alt, Shift, Win (display if they appear)',
	intro11: 'Backend service port number',
	intro12: 'Keystroke display only for active window',
	intro13: 'Use regular expression to match window process names',
	intro14: 'Shortcut key for toggling keystroke temporary display',
	intro15: 'Define shortcut keys. Changes take effect after program restarts.',
	intro16: 'Manually enter keystrokes',
	intro17: 'Real-time display interface for keystrokes',
	intro18: 'Width',
	intro19: 'Height',
	intro20: '0 means auto-adaptation',
	intro21: 'Background color and transparency',
	intro22: 'Mouse Penetration',
	intro23: 'Can click the app under the Popup',
	intro24: 'Font',
	intro25: 'Choose system fonts',
	intro26: 'Font size',
	intro27: 'Font type',
	intro28: 'Font color',
	intro29: 'Popup Fade delay(ms)',
	intro30: 'Interval of new Popup(ms)',
	intro31: 'Up, down, left, right position',
	intro32: 'Screen position of Popup appearance',
	intro33: 'Top-left',
	intro34: 'Top-right',
	intro35: 'Bottom-left',
	intro36: 'Bottom-right',
	intro37: 'Popup movement direction',
	intro38: 'Horizontal or vertical movement',
	intro39: 'Adjust position X',
	intro40: 'Horizontal position adjustment. Negative numbers indicate leftward movement and positive numbers indicate rightward movement.',
	intro41: 'Adjust Position Y',
	intro42: 'Vertical position adjustment. Negative numbers indicate upward movement and positive numbers indicate downward movement.',
	intro43: 'Enable DPI',
	intro44: 'Screen number',
	intro45: 'Screen Info is',
	intro46: 'Margin of Popup(px)',
	intro47: 'Have thin border',
	intro48: 'Key separator, used for displaying separation between keys',
	intro49: 'Recommended to use a space',
	intro50: 'Long press display, mainly used for control keys such as Ctrl, Alt, LWin, Shift, RWin, CapsLock, etc.',
	intro51: 'Control key X position',
	intro52: 'Control key Y position',
	intro53: 'Control key font size',
	intro54: 'Control key list',
	intro55: 'Which keys will not be displayed, but will be recorded',
	intro56: 'Parameters setting for the data statistics interface',
	intro57: 'First Screen size (in inches)',
	intro58: 'Used to calculate the cursor movement distance on the screen',
	intro59: 'Mouse DPI',
	intro60: 'Used to calculate the actual mouse movement distance',
	intro61: 'Key name',
	intro62: 'Symbol displayed for the key',
	intro63: 'Do not display or record',
	intro64: 'Do not display but record',
	intro65: 'Only display, do not record',
	intro66: 'Display and record',
	intro67: 'Normal',
	intro68: 'Bold',
	intro69: 'Italic',
	intro70: 'Strikethrough',
	intro71: 'Underline',
	intro72: 'Can not get Screen Info,please restart!',
	intro73: 'Data loading...',
	intro74: 'Loaded sucess!',
	intro75: 'Data saving...',
	intro76: 'Saved sucess!',
	intro77: '',
	intro78: 'Before',
	intro79: 'After',
	intro80: 'Expand',
	intro81: 'Reset',
	intro82: 'Save',
	intro83: 'Have changed, the client maybe restart for appling new parameter after saved',
	intro84: 'No changed',
	intro85:'Read data fail!',
	intro86:'Show in keyboard',
	intro87:'Other Keypress',
	intro88:'KeyName',
	intro89:'Key Description',
	intro90:'Key Count',
	intro91:'Now',
	intro92:'Will create a new time when client restart, today Time Range, from ',
	intro93:'to ',
	intro94:'Mouse movement distance (pixels)',
	intro95:'Mouse screen movement distance (meters)',
	intro96:'Mouse physical distance (meters)',
	intro97:'Mouse movement info',
	intro98:'Desc of distance',
	intro99:'Keyboard for data statistics',
	intro100:`The keyboard's define is composed of an array, each element is a 4-digit array. The first digit = X coordinate and the second digit = Y coordinate,
	The third digit is the symbol displayed on the keyboard (can be replaced by the key list), 
	and the fourth digit is the corresponding real key information, if empty, the third digit is default \n\n You can type and enter the new keyboard name in DropDownList`,
	intro101:"The keyboard's define is not valid format!",
	intro102:'Every keyboard define must be array, and lenth is 2-4 digits:',
	intro103:'1,2 digit of every keyboard define must be number:',
	intro104:'Apply',
	intro105:'Save New',
	intro106:'Delete',
	intro107:'Apply keyboard successful, you can check in data menu',
	intro108:'Save Update',
	intro109:'Confirm',
	intro110:'Cancel',
	intro111:'Successful',
	intro112:'Select Date',
	intro113:'Query',
	intro114:'Mouse Distance',
	intro115:'The sum of Mouse/keyboard Keypress ',
	intro116:'Top 10 OF keyboard keypress',
	intro117:'The format of date is invalid',
  }
};
